# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=20)),
                ('regionalism_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('house_name', models.CharField(max_length=20)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_type', models.CharField(max_length=20)),
                ('house_rent', models.CharField(max_length=20)),
                ('house_href', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
